### ISSUE TITLE
Problems compiling. Please supply installation instructions. 

### ISSUE THREAD

**Issue by theopathic** [whatdoineed2do/dvdpacking#1]
Please supply installation instructions.  I've encountered errors attempting compilation with

1. g++ (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)
2. Apple LLVM version 10.0.0 (clang-1000.10.44.4)

In addition, the Makefile has entries for including files from personal directories in /home/ray/tools that aren't in the github repo

CFLAGS=$(DEBUGFLAGS) -I/home/ray/tools/include -DNEED_UCHAR_UINT_T
CXXFLAGS=$(DEBUGFLAGS) -I/home/ray/tools -I/home/ray/tools/include -DNEED_UCHAR_UINT_T -g

**Comment by whatdoineed2do** [comment]
what are the errors you see?  i think theres expectation we are using a c++14 compiler.

the makefile is  poor and hardcoded -  i should clean them out for automake/autoconf but those flags dont impact compiling from somewhere else.

edit:
i've added the `automake/autoconf` to this to generate.  can you checkout and then from the toplevel:
```
autoreconf --install
autoconf
./configure && make
```

**Comment by theopathic** [comment]
1. g++ (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)

g++ -c -g  -I/home/ray/tools -I/home/ray/tools/include -DNEED_UCHAR_UINT_T -g Item.cc
In file included from Item.cc:1:0:
Item.h:21:20: error: expected ‘,’ or ‘...’ before ‘&&’ token
     Item(const Item&& rhs_) : _what(std::move(rhs_._what)), _size(rhs_._size)
                    ^
Item.h:21:27: error: invalid constructor; you probably meant ‘Item (const Item&)’
     Item(const Item&& rhs_) : _what(std::move(rhs_._what)), _size(rhs_._size)
                           ^
Item.h:24:36: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
     void operator=(const Item&)  = delete;
                                    ^
Item.h:25:30: error: expected ‘,’ or ‘...’ before ‘&&’ token
     void operator=(const Item&&) = delete;
                              ^
Item.h:25:36: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
     void operator=(const Item&&) = delete;
                                    ^
Item.cc: In constructor ‘Item::Item(const char*)’:
Item.cc:18:18: error: ‘nullptr’ was not declared in this scope
     if (what_ == nullptr) {
                  ^
Item.cc:25:66: error: ‘errno’ was not declared in this scope
         err << "failed to open '" << _what << "' - " << strerror(errno);
                                                                  ^
Item.cc: In member function ‘off_t Item::_du(const char*) const’:
Item.cc:56:35: error: ‘nullptr’ was not declared in this scope
     if ( (d = opendir(where_)) == nullptr) {
                                   ^
Item.cc:58:67: error: ‘errno’ was not declared in this scope
         err << "failed to open '" << where_ << "' - " << strerror(errno);
                                                                   ^
Item.cc:64:105: error: ‘malloc’ was not declared in this scope
     struct dirent*  dent = (struct dirent*)malloc(sizeof(struct dirent) + pathconf(where_, _PC_NAME_MAX));
                                                                                                         ^
Item.cc:65:30: error: ‘nullptr’ was not declared in this scope
     struct dirent*  result = nullptr;
                              ^
Item.cc:73:54: error: ‘sprintf’ was not declared in this scope
         sprintf(path, "%s/%s", where_, result->d_name);
                                                      ^
Item.cc:76:22: error: ‘free’ was not declared in this scope
             free(dent);
                      ^
Item.cc:79:69: error: ‘errno’ was not declared in this scope
             err << "failed to stat '" << path << "' - " << strerror(errno);
                                                                     ^
Item.cc:93:22: error: ‘free’ was not declared in this scope
             free(dent);
                      ^
Item.cc:98:14: error: ‘free’ was not declared in this scope
     free(dent);
              ^
Makefile:7: recipe for target 'Item.o' failed
make: *** [Item.o] Error 1


2. Apple LLVM version 10.0.0 (clang-1000.10.44.4)

c++ -c -g  -DNEED_UCHAR_UINT_T -g -fgnu-keywords Packer.cc
In file included from Packer.cc:9:
In file included from ./Packer.h:6:
In file included from ./Items.h:6:
./Item.h:21:20: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    Item(const Item&& rhs_) : _what(std::move(rhs_._what)), _size(rhs_._size)
                   ^
./Item.h:24:36: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
    void operator=(const Item&)  = delete;
                                   ^
./Item.h:25:30: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    void operator=(const Item&&) = delete;
                             ^
./Item.h:25:36: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
    void operator=(const Item&&) = delete;
                                   ^
In file included from Packer.cc:9:
In file included from ./Packer.h:6:
In file included from ./Items.h:7:
./Container.h:31:30: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    Container(const Container&& rhs_) : _size(rhs_._size), _c(std::move(rhs_._c))
                             ^
./Container.h:43:25: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    void  emplace_back(T&& i_)
                        ^
In file included from Packer.cc:9:
In file included from ./Packer.h:6:
./Items.h:9:15: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
using Items = Container<Item>;
              ^
In file included from Packer.cc:9:
In file included from ./Packer.h:7:
In file included from ./Bins.h:6:
./Bin.h:20:18: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    Bin(const Bin&& rhs_) : _max(rhs_._max), _remain(rhs_._remain), _items(std::move(rhs_._items)), _closed(rhs_._closed) { }
                 ^
./Bin.h:22:35: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
    void operator=(const Bin&)  = delete;
                                  ^
./Bin.h:23:29: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    void operator=(const Bin&&) = delete;
                            ^
./Bin.h:23:35: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
    void operator=(const Bin&&) = delete;
                                  ^
In file included from Packer.cc:9:
In file included from ./Packer.h:7:
./Bins.h:9:14: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
using Bins = Container<Bin>;
             ^
Packer.cc:19:47: error: expected expression
    std::all_of(items_.begin(), items_.end(), [&bins, &binsz_, &unhandled_](const Item& i) {
                                              ^
Packer.cc:64:47: error: expected expression
    std::all_of(items_.begin(), items_.end(), [&bins, &binsz_, &unhandled_](const Item& i) {
                                              ^
Packer.cc:111:47: error: expected expression
    std::all_of(items_.begin(), items_.end(), [&bins, &binsz_, &unhandled_](const Item& i) {
                                              ^
In file included from Packer.cc:9:
In file included from ./Packer.h:6:
In file included from ./Items.h:6:
In file included from ./Item.h:9:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/string:477:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/string_view:176:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/__string:56:
/Library/Developer/CommandLineTools/usr/include/c++/v1/algorithm:719:71: error: invalid operands to binary expression ('const Item' and 'const Item')
    bool operator()(const _T1& __x, const _T1& __y) const {return __x < __y;}
                                                                  ~~~ ^ ~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/list:2253:13: note: in instantiation of member function 'std::__1::__less<Item, Item>::operator()' requested here
        if (__comp(*--__e2, *__f1))
            ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/list:2239:5: note: in instantiation of function template specialization 'std::__1::list<Item, std::__1::allocator<Item> >::__sort<std::__1::__less<Item, Item> >' requested here
    __sort(begin(), end(), base::__sz(), __comp);
    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/list:2230:5: note: in instantiation of function template specialization 'std::__1::list<Item, std::__1::allocator<Item> >::sort<std::__1::__less<Item, Item> >' requested here
    sort(__less<value_type>());
    ^
Packer.cc:53:7: note: in instantiation of member function 'std::__1::list<Item, std::__1::allocator<Item> >::sort' requested here
    l.sort();
      ^
./Item.h:31:11: note: candidate function not viable: 'this' argument has type 'const Item', but method is not marked const
    bool  operator<(const Item& rhs_)  { return _size < rhs_._size; }
          ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/utility:572:1: note: candidate template ignored: could not match 'pair<type-parameter-0-0, type-parameter-0-1>' against 'const Item'
operator< (const pair<_T1,_T2>& __x, const pair<_T1,_T2>& __y)
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:702:1: note: candidate template ignored: could not match 'reverse_iterator<type-parameter-0-0>' against 'const Item'
operator<(const reverse_iterator<_Iter1>& __x, const reverse_iterator<_Iter2>& __y)
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:1143:1: note: candidate template ignored: could not match 'move_iterator<type-parameter-0-0>' against 'const Item'
operator<(const move_iterator<_Iter1>& __x, const move_iterator<_Iter2>& __y)
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:1512:1: note: candidate template ignored: could not match '__wrap_iter<type-parameter-0-0>' against 'const Item'
operator<(const __wrap_iter<_Iter1>& __x, const __wrap_iter<_Iter2>& __y) _NOEXCEPT_DEBUG
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:2920:1: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'const Item'
operator< (const unique_ptr<_T1, _D1>& __x, const unique_ptr<_T2, _D2>& __y)
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:2978:1: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'const Item'
operator<(const unique_ptr<_T1, _D1>& __x, nullptr_t)
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:2987:1: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'const Item'
operator<(nullptr_t, const unique_ptr<_T1, _D1>& __x)
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:4758:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'const Item'
operator<(const shared_ptr<_Tp>& __x, const shared_ptr<_Up>& __y) _NOEXCEPT
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:4823:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'const Item'
operator<(const shared_ptr<_Tp>& __x, nullptr_t) _NOEXCEPT
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:4831:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'const Item'
operator<(nullptr_t, const shared_ptr<_Tp>& __x) _NOEXCEPT
^
12 warnings and 4 errors generated.
make: *** [Packer.o] Error 1

**Comment by whatdoineed2do** [comment]
Delete your tree and checkout master again

It looks like your compilers need to be told which c++ std to use and its defaulting to c++03 - the master branch should fix this. See INSTALL file to generate the new makefile

**Comment by theopathic** [comment]
1. g++ (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)

Compiles and runs!

2. Apple LLVM version 10.0.0 (clang-1000.10.44.4)

/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in src
  CXX      dvdpacking-Bin.o
  CXX      dvdpacking-Item.o
  CXX      dvdpacking-Packer.o
In file included from Packer.cc:9:
In file included from ./Packer.h:6:
In file included from ./Items.h:6:
In file included from ./Item.h:9:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/string:477:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/string_view:176:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/__string:56:
/Library/Developer/CommandLineTools/usr/include/c++/v1/algorithm:719:71: error: invalid operands to binary expression ('const Item' and 'const Item')
    bool operator()(const _T1& __x, const _T1& __y) const {return __x < __y;}
                                                                  ~~~ ^ ~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/list:2253:13: note: in instantiation of member function 'std::__1::__less<Item, Item>::operator()' requested here
        if (__comp(*--__e2, *__f1))
            ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/list:2239:5: note: in instantiation of function template specialization 'std::__1::list<Item, std::__1::allocator<Item> >::__sort<std::__1::__less<Item, Item> >' requested here
    __sort(begin(), end(), base::__sz(), __comp);
    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/list:2230:5: note: in instantiation of function template specialization 'std::__1::list<Item, std::__1::allocator<Item> >::sort<std::__1::__less<Item, Item> >' requested here
    sort(__less<value_type>());
    ^
Packer.cc:53:7: note: in instantiation of member function 'std::__1::list<Item, std::__1::allocator<Item> >::sort' requested here
    l.sort();
      ^
./Item.h:31:11: note: candidate function not viable: 'this' argument has type 'const Item', but method is not marked const
    bool  operator<(const Item& rhs_)  { return _size < rhs_._size; }
          ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/utility:572:1: note: candidate template ignored: could not match 'pair<type-parameter-0-0, type-parameter-0-1>' against 'const Item'
operator< (const pair<_T1,_T2>& __x, const pair<_T1,_T2>& __y)
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:702:1: note: candidate template ignored: could not match 'reverse_iterator<type-parameter-0-0>' against 'const Item'
operator<(const reverse_iterator<_Iter1>& __x, const reverse_iterator<_Iter2>& __y)
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:1143:1: note: candidate template ignored: could not match 'move_iterator<type-parameter-0-0>' against 'const Item'
operator<(const move_iterator<_Iter1>& __x, const move_iterator<_Iter2>& __y)
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:1512:1: note: candidate template ignored: could not match '__wrap_iter<type-parameter-0-0>' against 'const Item'
operator<(const __wrap_iter<_Iter1>& __x, const __wrap_iter<_Iter2>& __y) _NOEXCEPT_DEBUG
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/tuple:1187:1: note: candidate template ignored: could not match 'tuple<type-parameter-0-0...>' against 'const Item'
operator<(const tuple<_Tp...>& __x, const tuple<_Up...>& __y)
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:2920:1: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'const Item'
operator< (const unique_ptr<_T1, _D1>& __x, const unique_ptr<_T2, _D2>& __y)
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:2978:1: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'const Item'
operator<(const unique_ptr<_T1, _D1>& __x, nullptr_t)
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:2987:1: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'const Item'
operator<(nullptr_t, const unique_ptr<_T1, _D1>& __x)
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:4758:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'const Item'
operator<(const shared_ptr<_Tp>& __x, const shared_ptr<_Up>& __y) _NOEXCEPT
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:4823:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'const Item'
operator<(const shared_ptr<_Tp>& __x, nullptr_t) _NOEXCEPT
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:4831:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'const Item'
operator<(nullptr_t, const shared_ptr<_Tp>& __x) _NOEXCEPT
^
In file included from Packer.cc:9:
In file included from ./Packer.h:6:
In file included from ./Items.h:6:
In file included from ./Item.h:9:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/string:477:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/string_view:176:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/__string:56:
/Library/Developer/CommandLineTools/usr/include/c++/v1/algorithm:719:71: error: invalid operands to binary expression ('const Bin' and 'const Bin')
    bool operator()(const _T1& __x, const _T1& __y) const {return __x < __y;}
                                                                  ~~~ ^ ~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/list:2253:13: note: in instantiation of member function 'std::__1::__less<Bin, Bin>::operator()' requested here
        if (__comp(*--__e2, *__f1))
            ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/list:2239:5: note: in instantiation of function template specialization 'std::__1::list<Bin, std::__1::allocator<Bin> >::__sort<std::__1::__less<Bin, Bin> >' requested here
    __sort(begin(), end(), base::__sz(), __comp);
    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/list:2230:5: note: in instantiation of function template specialization 'std::__1::list<Bin, std::__1::allocator<Bin> >::sort<std::__1::__less<Bin, Bin> >' requested here
    sort(__less<value_type>());
    ^
./Container.h:72:24: note: in instantiation of member function 'std::__1::list<Bin, std::__1::allocator<Bin> >::sort' requested here
    void  sort()  { _c.sort(); }
                       ^
Packer.cc:89:14: note: in instantiation of member function 'Container<Bin>::sort' requested here
        bins.sort();
             ^
./Bin.h:38:11: note: candidate function not viable: 'this' argument has type 'const Bin', but method is not marked const
    bool  operator<(const Bin& rhs_)
          ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/utility:572:1: note: candidate template ignored: could not match 'pair<type-parameter-0-0, type-parameter-0-1>' against 'const Bin'
operator< (const pair<_T1,_T2>& __x, const pair<_T1,_T2>& __y)
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:702:1: note: candidate template ignored: could not match 'reverse_iterator<type-parameter-0-0>' against 'const Bin'
operator<(const reverse_iterator<_Iter1>& __x, const reverse_iterator<_Iter2>& __y)
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:1143:1: note: candidate template ignored: could not match 'move_iterator<type-parameter-0-0>' against 'const Bin'
operator<(const move_iterator<_Iter1>& __x, const move_iterator<_Iter2>& __y)
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:1512:1: note: candidate template ignored: could not match '__wrap_iter<type-parameter-0-0>' against 'const Bin'
operator<(const __wrap_iter<_Iter1>& __x, const __wrap_iter<_Iter2>& __y) _NOEXCEPT_DEBUG
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/tuple:1187:1: note: candidate template ignored: could not match 'tuple<type-parameter-0-0...>' against 'const Bin'
operator<(const tuple<_Tp...>& __x, const tuple<_Up...>& __y)
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:2920:1: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'const Bin'
operator< (const unique_ptr<_T1, _D1>& __x, const unique_ptr<_T2, _D2>& __y)
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:2978:1: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'const Bin'
operator<(const unique_ptr<_T1, _D1>& __x, nullptr_t)
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:2987:1: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'const Bin'
operator<(nullptr_t, const unique_ptr<_T1, _D1>& __x)
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:4758:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'const Bin'
operator<(const shared_ptr<_Tp>& __x, const shared_ptr<_Up>& __y) _NOEXCEPT
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:4823:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'const Bin'
operator<(const shared_ptr<_Tp>& __x, nullptr_t) _NOEXCEPT
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:4831:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'const Bin'
operator<(nullptr_t, const shared_ptr<_Tp>& __x) _NOEXCEPT
^
2 errors generated.
make[2]: *** [dvdpacking-Packer.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by whatdoineed2do** [comment]
I haven't got `clang` on this machine but it looks like `clang` is complaining about const-ness.

I've added one more commit - can you pull from master one more time and compile on apple; if that still doesnt work i'll try to get a `clang` env to look again

**Comment by theopathic** [comment]
Didn't try the Fedora build, but the Apple autoreconfig fails:

% autoreconf --install
configure.ac:12: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:12: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:12: the top level
configure.ac:30: warning: AC_OUTPUT should be used without arguments.
configure.ac:30: You should run autoupdate.
configure.ac:3: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:14: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: error: /opt/local/bin/autoconf failed with exit status: 1

I ran autoupdate, but it didn't help.  I using autoconf 2.71.

**Comment by whatdoineed2do** [comment]
i've dropped both of these redundant items.  can you delete and take a clean checkout and try again -  hopefully that will be it.  my fedora box has `autoconf 2.69`

if there are compilation failures regarding `readdir_r()`, run configure with `--enable-17-readdir` whcih will use the c++ filesystem library available in c++17
